#define MAX_CATEGORIES		 256
#define MAX_ITEMS					 256

#define HUB_PHRASE_SOMETHING_WENT_WRONG "Hub_Core_Something_Went_Wrong"


// Shop Phrases
#define HUB_PHRASE_YOU_ALREADY_OWN_THIS_ITEM "Hub_You_Already_Own_This_Item"
#define HUB_PHRASE_YOU_DONT_HAVE_ENOUGH_CREDITS_TO_BUY_THIS "Hub_You_Dont_Have_Enough_Credits_To_Buy_This"
#define HUB_PHRASE_SUCCESSFULLY_BOUGHT_ITEM "Hub_Successfully_Bought_Item"
#define HUB_PHRASE_SHOP_CONFIRM_BUY "Hub_Shop_Confirm_Buy"

// Credit phrases
#define HUB_PHRASE_PLAYER_CREDITS "Hub_Player_Credits"
#define HUB_PHRASE_CREDITS_COINFLIP_USAGE "Hub_Credits_Coinflip_Usage"
#define HUB_PHRASE_CREDITS_COINFLIP_NOT_ENOUGH_CREDITS "Hub_Credits_Coinflip_Not_Enough_Credits"
#define HUB_PHRASE_CREDITS_COINFLIP_WIN "Hub_Credits_Coinflip_Win"
#define HUB_PHRASE_CREDITS_COINFLIP_LOSE "Hub_Credits_Coinflip_Lose"
#define HUB_PHRASE_PLAYER_RECIEVE_CREDITS "Hub_Player_Recieve_Credits"

